[package]
name = "wlogout2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.9.4", package = "gtk4" }
gtk4-layer-shell = "0.4.0"

