name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install linux dependencies
      run: sudo apt install -y libglib2.0-dev zlib1g-dev libpango1.0-dev libgtk-4-dev libgdk-pixbuf2.0-dev # libgtk4-layer-shell-dev
    - name: Build gtk4-layer-shell while it is not published on ubuntu
      shell: bash
      run: |
          sudo apt install meson libwayland-dev libgtk-4-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools valac
          cd ..
          git clone https://github.com/wmww/gtk4-layer-shell.git
          cd gtk4-layer-shell
          meson setup -Dexamples=true -Ddocs=true -Dtests=true build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
          cd ..
          cd wlogout2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
